steps:
  - id: Install
    name: node:10-alpine
    entrypoint: yarn
    secretEnv: ['NPM_TOKEN']
    args: ['install']

  - id: Build
    name: node:10-alpine
    entrypoint: yarn
    secretEnv: ['NPM_TOKEN']
    args: ['build']

  - id: Publish on NPM
    name: node:10
    secretEnv: ['NPM_TOKEN']
    entrypoint: bash
    args:
      - '-c'
      - |
        if [[ "$BRANCH_NAME" == "master" ]]; then npm publish --access public; else echo "'master' branch not detected"; fi

secrets:
  - kmsKeyName: projects/anthor-general/locations/global/keyRings/services/cryptoKeys/NPM_TOKEN
    secretEnv:
      NPM_TOKEN: CiQAjTohlA9eMLGdQ+hHtsI3JNPC1XU5ei2ZDInB1iLr9FaSI+0STQD4MI/q1/eFQplsPS49Odi0paPVF8fqQsrs60OL256pP2QYdXyxoyMRsW+Q8OcyyEnpAsIT7J4z/X/MAC3UzALPXK8qsQg5njZqrnnt
